<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Paired t-test and ANOVA – UNE Course</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./chapter4.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="include/webex.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter5.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Paired t-test and ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UNE Course</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting to Know Your Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests: one sample and two sample</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Paired t-test and ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#hypothesis-tests-using-the-t-distribution" id="toc-hypothesis-tests-using-the-t-distribution" class="nav-link active" data-scroll-target="#hypothesis-tests-using-the-t-distribution"><span class="header-section-number">7</span> <strong>Hypothesis tests using the t-distribution</strong></a></li>
  <li><a href="#paired-t-test" id="toc-paired-t-test" class="nav-link" data-scroll-target="#paired-t-test"><span class="header-section-number">8</span> Paired t-test</a>
  <ul class="collapse">
  <li><a href="#write-hypotheses" id="toc-write-hypotheses" class="nav-link" data-scroll-target="#write-hypotheses"><span class="header-section-number">8.0.1</span> Write Hypotheses</a></li>
  </ul></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova"><span class="header-section-number">9</span> ANOVA</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Paired t-test and ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="hypothesis-tests-using-the-t-distribution" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> <strong>Hypothesis tests using the t-distribution</strong></h1>
<p><img src="images/clipboard-312548449.png" class="img-fluid"></p>
</section>
<section id="paired-t-test" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Paired t-test</h1>
<p>The next dataset we will be using comes from the Living Well Multicultural – Lifestyle Modification Program. This file contains paired pre- and post-intervention measurements for adults who participated in the program between 2014 and 2017.</p>
<p>You can then save the file in your Datasets folder in your InferentialStats project folder that you created in the Introduction. You can give it a new name so that it is easier to call into R Studio.</p>
<p>If you open the file, you may notice that the first row is simply a title. We can ignore the title by including <code>skip</code> when we load in the data.</p>
<p>Once you’ve saved the file, you can load the dataset into R by typing:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>living_well <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data sets/Cleaned_data_pre_post.csv"</span>, </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can take a look at the data to ensure it has been loaded in correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(living_well)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1112 obs. of  100 variables:
 $ Time           : Factor w/ 2 levels "Baseline","Post week8": 1 1 1 1 1 1 1 1 2 2 ...
 $ Community      : Factor w/ 9 levels "Afghani","Arabic-speaking",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ Location       : Factor w/ 30 levels "44","Acacia Ridge",..: 6 6 6 6 6 6 6 6 6 6 ...
 $ ID             : Factor w/ 554 levels "ABA200879","ABD 010160",..: 295 294 38 296 191 192 297 10 295 294 ...
 $ Drop_yn        : Factor w/ 1 level "Complete": 1 1 1 1 1 1 1 1 1 1 ...
 $ Dose_yn        : Factor w/ 2 levels "&lt;=6 doses, Incomplete",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ Dose           : int  8 8 8 8 7 7 7 8 8 8 ...
 $ Age            : int  21 20 49 19 52 20 22 55 21 20 ...
 $ Gender         : Factor w/ 2 levels "Female","Male": 2 1 1 1 2 2 1 2 2 1 ...
 $ Country_b      : Factor w/ 23 levels "1 Afghanistan",..: 22 22 22 22 22 17 22 22 22 22 ...
 $ Country_b_other: Factor w/ 21 levels " ","Australia",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Time_aus       : Factor w/ 6 levels "&gt;20 years","1-5 years",..: 2 4 3 4 3 3 3 4 2 4 ...
 $ language       : Factor w/ 18 levels " ","1 Arabic",..: 2 2 3 2 3 17 17 2 2 2 ...
 $ language_others: Factor w/ 51 levels " ","20 Samoan",..: 25 25 1 25 1 1 1 1 25 25 ...
 $ Ethnicity      : Factor w/ 82 levels " ","Acholi","Afghan",..: 1 1 1 1 1 1 1 35 1 1 ...
 $ Postcode_SEIFA : Factor w/ 4 levels "999","High","Low",..: 4 4 2 4 2 2 2 4 4 4 ...
 $ Postcode       : int  4109 4109 4152 4109 4152 4152 4152 4109 4109 4109 ...
 $ Edu_combine    : Factor w/ 5 levels "999","Bachelor‎/Postgraduate",..: 3 3 5 3 3 3 2 5 3 3 ...
 $ Education      : Factor w/ 8 levels "999","Bachelor degree",..: 6 6 4 6 5 5 2 4 6 6 ...
 $ Country_Q      : Factor w/ 4 levels " ","999","Australia",..: 3 3 4 3 4 3 3 4 3 3 ...
 $ Employ_comb    : Factor w/ 5 levels "999","No paid work",..: 4 4 3 4 3 4 5 5 4 4 ...
 $ Employment     : Factor w/ 11 levels "999","Casual paid work",..: 9 9 7 9 6 9 2 2 9 9 ...
 $ Household      : Factor w/ 6 levels "999","Couple, no children",..: 6 6 3 6 3 6 6 3 6 6 ...
 $ Referral       : Factor w/ 13 levels " ","1 ECCQ website/newsletter",..: 1 9 9 9 9 3 3 9 1 9 ...
 $ Weight         : num  55.5 48.5 88.9 52.3 90.7 75.7 54 77 55 48 ...
 $ Height         : num  167 161 160 159 173 ...
 $ BMI_cate2      : Factor w/ 5 levels "999","Normal weight",..: 2 2 3 2 3 2 2 4 2 2 ...
 $ BMI_cate1      : Factor w/ 5 levels "999","Normal weight",..: 2 2 3 2 3 2 2 4 2 2 ...
 $ BMI            : num  19.9 18.8 34.6 20.8 30.3 24.5 21.5 26.2 19.7 18.6 ...
 $ Waist          : num  74 71 106 70 102 ...
 $ Risk_new       : Factor w/ 3 levels "999","No","Yes": 2 2 3 2 3 2 2 2 2 2 ...
 $ Risk           : Factor w/ 4 levels " ","999","No",..: 3 3 4 3 4 3 3 3 3 3 ...
 $ WHtR_yn        : Factor w/ 3 levels "999","High risk",..: 3 3 2 3 2 2 3 2 3 3 ...
 $ WHtR           : num  0.44 0.44 0.66 0.44 0.59 0.53 0.46 0.56 0.44 0.44 ...
 $ BP_systolic    : int  110 88 111 110 140 109 110 146 90 102 ...
 $ BP_diastolic   : int  70 54 63 60 58 59 64 78 75 60 ...
 $ High_BP        : Factor w/ 4 levels " ","999","No",..: 3 3 3 3 3 3 3 4 3 3 ...
 $ Weight_pc_cate : Factor w/ 6 levels "999","A healthy weight",..: 2 3 3 6 3 3 4 3 2 2 ...
 $ Weight_pc      : Factor w/ 7 levels " ","1 A healthy weight",..: 2 3 3 5 3 3 6 3 2 2 ...
 $ Weight_stt     : Factor w/ 6 levels " ","1 Lost weight",..: 5 3 4 3 2 3 4 3 4 2 ...
 $ Chronic_con    : Factor w/ 4 levels " ","999","No",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Chronic_name   : Factor w/ 174 levels " ","Arteritis",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Smoke_stt      : Factor w/ 4 levels " ","999","No",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Smoke_re       : Factor w/ 8 levels " ","3","999",..: 4 4 4 4 4 4 4 4 4 4 ...
 $ Smoke_num      : Factor w/ 24 levels " ","0","0 (quit)",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Alcohol_stt    : Factor w/ 4 levels " ","999","No",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Alcohol_safe   : Factor w/ 4 levels " ","999","Not safe",..: NA NA NA NA NA NA NA NA NA NA ...
 $ Alcohol_re     : Factor w/ 5 levels " ","999","I don't consume alcohol",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Alcohol_freq   : Factor w/ 9 levels " ","1 Everyday",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Alcohol_amt    : Factor w/ 6 levels " ","1 Less than 1",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Fruit_yn       : Factor w/ 3 levels "999","Meet the guideline",..: 2 2 2 2 2 3 2 2 2 2 ...
 $ Fruit_cate     : Factor w/ 8 levels " ","999","Don't eat fruit",..: 4 8 7 4 4 6 4 4 7 7 ...
 $ Fruit          : Factor w/ 9 levels " ","0 Don't eat fruit",..: 8 6 7 8 8 5 8 8 7 7 ...
 $ Vegetables_yn  : Factor w/ 3 levels "999","Don't meet the guideline",..: 2 2 2 2 2 2 2 2 2 3 ...
 $ Veggie_cate    : Factor w/ 9 levels " ","999","Don't eat vegetables",..: 7 8 6 8 8 3 8 7 9 4 ...
 $ Veggie         : Factor w/ 10 levels " ","0 Don't eat vegetables",..: 5 7 4 7 7 2 7 5 6 9 ...
 $ Milk_combine   : Factor w/ 5 levels " ","999","Full fat‎/cream",..: 3 5 4 3 3 3 3 3 4 4 ...
 $ Milk_cate      : Factor w/ 10 levels " ","999","Don't consume any milk",..: 10 3 6 10 10 10 10 10 6 6 ...
 $ Milk           : Factor w/ 14 levels " ","0 Don't consume any milk",..: 5 4 6 5 5 5 5 5 6 6 ...
 $ Takeaway_comb  : Factor w/ 5 levels "&lt;= 1 a week",..: 3 1 1 3 1 5 1 1 1 1 ...
 $ Takeaway_cate  : Factor w/ 9 levels " ","2-3 times per week",..: 2 7 7 2 7 8 7 7 9 7 ...
 $ Takeaway       : Factor w/ 10 levels " ","0 Never or rarely",..: 5 3 3 5 3 2 3 3 4 3 ...
 $ Chips_comb     : Factor w/ 6 levels " ","&lt;=1 per week",..: 4 2 2 2 2 6 2 2 2 2 ...
 $ Chips_cate     : Factor w/ 9 levels " ","2-3 times per week",..: 2 9 7 9 7 8 7 7 7 7 ...
 $ Chips          : Factor w/ 12 levels " ","0 Never or rarely",..: 6 5 4 5 4 2 4 4 4 4 ...
 $ Salty_snk3gr   : Factor w/ 5 levels " ","1-3 times‎ per week",..: 2 2 5 2 5 2 5 5 5 5 ...
 $ Salty_snk_new  : Factor w/ 6 levels " ","&gt;=4 times‎/week",..: 3 3 5 3 6 3 6 5 6 6 ...
 $ Salty_snk_cate : Factor w/ 8 levels " ","1-3 times week",..: 2 2 6 2 7 2 7 6 7 7 ...
 $ Salty_snk      : Factor w/ 8 levels " ","0 Never or rarely",..: 4 4 3 4 2 4 2 3 2 2 ...
 $ Sweet_snk3gr   : Factor w/ 5 levels " ","1-3 times per week",..: 3 5 2 3 5 2 2 3 5 5 ...
 $ Sweet_snk_cate : Factor w/ 8 levels " ","2 or more times per day",..: 5 7 4 2 6 4 4 8 6 6 ...
 $ Sweet_snk      : Factor w/ 9 levels " ","0 Don’t consume any milk",..: 6 3 5 8 4 5 5 7 4 4 ...
 $ Softdrink_3gr  : Factor w/ 4 levels "1-3 times per week",..: 2 4 1 4 1 2 4 1 1 4 ...
 $ Softdrink_cate : Factor w/ 8 levels " ","2 or more times per day",..: 2 7 4 7 4 8 6 4 4 6 ...
 $ Softdrink      : Factor w/ 8 levels " ","0 Never or rarely",..: 7 2 4 2 4 6 3 4 4 3 ...
 $ Pr_meat_3gr    : Factor w/ 4 levels "1-2 times per week",..: 2 1 4 2 1 2 4 4 4 4 ...
 $ Pr_meat        : Factor w/ 7 levels " ","1-2 times per week",..: 4 2 6 4 2 3 6 6 6 6 ...
 $ Processed_meat : Factor w/ 7 levels " ","0 Never or rarely",..: 6 4 3 6 4 5 3 3 3 3 ...
 $ Vegetarian     : Factor w/ 11 levels " ","30","300",..: 10 10 10 10 10 10 10 10 10 10 ...
 $ Walking        : int  90 95 0 120 45 100 200 120 120 250 ...
 $ Vigorous_lb    : int  60 100 30 30 150 10 200 900 60 70 ...
 $ Md_act         : int  60 30 5 10 0 0 30 90 60 30 ...
 $ Vigorous_act   : int  30 30 0 15 0 0 100 90 120 250 ...
 $ Act_comp_cate  : Factor w/ 7 levels "999","A little less",..: 3 6 3 6 5 6 4 4 3 7 ...
 $ Act_comparison : Factor w/ 8 levels " ","1 Significantly less",..: 5 2 5 2 7 2 4 4 5 6 ...
 $ KL1            : Factor w/ 8 levels " ","999","A",..: 7 6 6 4 8 5 6 6 6 6 ...
 $ KL2            : Factor w/ 8 levels " ","999","A",..: 8 5 8 5 8 3 3 6 3 3 ...
 $ KL3            : Factor w/ 8 levels " ","999","A",..: 6 5 5 5 8 7 7 5 5 5 ...
 $ KL4            : Factor w/ 7 levels " ","999","A",..: 4 6 5 5 6 6 6 6 6 6 ...
 $ KL5            : Factor w/ 7 levels " ","999","A",..: 7 7 3 4 7 5 7 5 5 5 ...
 $ KL6            : Factor w/ 7 levels " ","999","A",..: 7 4 7 5 7 7 6 5 6 6 ...
 $ KL7            : Factor w/ 7 levels " ","999","A",..: 5 5 6 6 5 5 5 5 5 5 ...
 $ conf_risk      : int  10 8 8 10 1 7 7 9 9 10 ...
 $ conf_manage    : int  10 8 8 10 1 6 7 10 9 10 ...
 $ Physic_act_yn  : Factor w/ 3 levels "999","No","Yes": 3 3 2 3 3 2 3 3 3 3 ...
 $ Physic_moderate: int  150 125 5 130 45 100 230 210 180 280 ...
 $ Physic_vigo    : int  90 130 30 45 150 10 300 990 180 320 ...
 $ Physic_all     : int  240 255 35 175 195 110 530 1200 360 600 ...
 $ Knowledge      : int  1 4 2 1 2 3 4 5 6 6 ...
  [list output truncated]</code></pre>
</div>
</div>
<ol type="1">
<li>How many variables are there? <input class="webex-solveme nospaces" size="3" data-answer="[&quot;100&quot;]"></li>
<li>How many observations are there? <input class="webex-solveme nospaces" size="4" data-answer="[&quot;1112&quot;]"></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(living_well<span class="sc">$</span>Time)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Baseline   Post week8
Levels: Baseline Post week8</code></pre>
</div>
</div>
<p>If we look at the <code>Time</code> variable, we can see that there are two levels: <code>Baseline</code> and <code>Post week8</code>. We also have an <code>ID</code> variable, which indicates that we have a repeated measurement for the baseline and post week 8 measurements. As we have one row for each measurement, this means our data is in <strong>long format</strong>. Another way to think about long format is that the same participant appears multiple times in the data set.</p>
<p>To be able to perform a paired t-test to compare the pre- and post-measurements, we need to convert the data to <strong>wide format</strong>. This means that we want one row per participant, with separate columns for each time point, such as a pre value and post value in the same row.</p>
<p>You may notice that there are many rows that have observations recorded as <code>999</code>. At times, <code>999</code> is used as a placeholder for <code>NA</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>living_well_wide <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  living_well,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id_cols =</span> ID,               </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_from =</span> Time,          </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_from =</span> BMI           </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `BMI` are not uniquely identified; output will contain list-cols.
• Use `values_fn = list` to suppress this warning.
• Use `values_fn = {summary_fun}` to summarise duplicates.
• Use the following dplyr code to identify duplicates.
  {data} |&gt;
  dplyr::summarise(n = dplyr::n(), .by = c(ID, Time)) |&gt;
  dplyr::filter(n &gt; 1L)</code></pre>
</div>
</div>
<p>You can see an error appears when we try to convert the data. This is telling us there are duplicates for the ID beyond the two that we are expecting. Let’s try using the code provided in the warning to see what’s going on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>living_well <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> dplyr<span class="sc">::</span><span class="fu">n</span>(), <span class="at">.by =</span> <span class="fu">c</span>(ID, Time)) <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>L)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          ID       Time n
1  PIR201181   Baseline 2
2  PIR201181 Post week8 2
3 ABD 010187   Baseline 2
4 ABD 010187 Post week8 2</code></pre>
</div>
</div>
<p>There are four IDs that have two baseline measurements and two post week8 measurements. Let’s investigate these rows closer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>living_well[living_well<span class="sc">$</span>ID <span class="sc">==</span> <span class="st">"PIR201181"</span>, <span class="fu">c</span>(<span class="st">"ID"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Time"</span>, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"BMI"</span>, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Weight"</span>) ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           ID       Time  BMI Weight
647 PIR201181   Baseline 27.5   74.3
651 PIR201181   Baseline 21.0   50.4
655 PIR201181 Post week8 26.2   71.0
659 PIR201181 Post week8 21.0   49.7</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>living_well[living_well<span class="sc">$</span>ID <span class="sc">==</span> <span class="st">"ABD 010187"</span>, <span class="fu">c</span>(<span class="st">"ID"</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Time"</span>, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"BMI"</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                                             <span class="st">"Weight"</span>) ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            ID       Time  BMI Weight
813 ABD 010187   Baseline 26.4   63.4
816 ABD 010187   Baseline 21.7   59.0
831 ABD 010187 Post week8 26.7   64.2
834 ABD 010187 Post week8 26.7   64.2</code></pre>
</div>
</div>
<p>This confirms what we expected - that there are four measurements per ID, when we were expecting two. This was likely a data entry error, which can happen in real world datasets. It is impossible to tell which pre- and post-measurements match each other, so the safest option is to drop these observations. As we have 1112 observations, this shouldn’t impact our analysis too much.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>bad_ID <span class="ot">&lt;-</span> living_well <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="at">n =</span> dplyr<span class="sc">::</span><span class="fu">n</span>(), <span class="at">.by =</span> <span class="fu">c</span>(ID, Time)) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>L) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(ID)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>living_well_clean <span class="ot">&lt;-</span> living_well <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>ID <span class="sc">%in%</span> bad_ID<span class="sc">$</span>ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s try convert our data to wide format again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>living_well_wide <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  living_well_clean,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">id_cols =</span> ID,               </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_from =</span> Time,          </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_from =</span> BMI,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_glue =</span> <span class="st">"{str_replace_all(Time, ' ', '_')}"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>No warning this time! That’s a good sign our method worked. Let’s take a look at our dataset now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(living_well_wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [552 × 3] (S3: tbl_df/tbl/data.frame)
 $ ID        : Factor w/ 554 levels "ABA200879","ABD 010160",..: 295 294 38 296 191 192 297 10 453 452 ...
 $ Baseline  : num [1:552] 19.9 18.8 34.6 20.8 30.3 24.5 21.5 26.2 19.6 19.9 ...
 $ Post_week8: num [1:552] 19.7 18.6 33.7 19.6 30.2 24.3 20.7 25.7 19.5 19.8 ...</code></pre>
</div>
</div>
<ol type="1">
<li>How many variables are there? <input class="webex-solveme nospaces" size="1" data-answer="[&quot;3&quot;]"></li>
<li>How many observations are there? <input class="webex-solveme nospaces" size="3" data-answer="[&quot;552&quot;]"></li>
</ol>
<p>Remember, we have 552 observations now because we combined the pre- and post-measurements into one row. We started with 1112, removed 8, and then combined the two measurements which results in 552.</p>
<p>Now we can check if there are any 999 values and drop them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(living_well_wide<span class="sc">$</span>Baseline <span class="sc">==</span> <span class="dv">999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(living_well_wide<span class="sc">$</span>Post_week8<span class="sc">==</span> <span class="dv">999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>As we have TRUE for both variables, we can convert the 999 to NA and then remove.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>living_well_wide <span class="ot">&lt;-</span> living_well_wide <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Baseline =</span> <span class="fu">na_if</span>(Baseline, <span class="dv">999</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Post_week8 =</span> <span class="fu">na_if</span>(Post_week8, <span class="dv">999</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(Baseline, Post_week8)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(living_well_wide<span class="sc">$</span>Baseline <span class="sc">==</span> <span class="dv">999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(living_well_wide<span class="sc">$</span>Post_week8<span class="sc">==</span> <span class="dv">999</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>We have officially cleaned our data! We can now get into our statistical analysis.</p>
<section id="write-hypotheses" class="level3" data-number="8.0.1">
<h3 data-number="8.0.1" class="anchored" data-anchor-id="write-hypotheses"><span class="header-section-number">8.0.1</span> Write Hypotheses</h3>
<p>Because we are keeping the dataset simple, a natural research question is whether there is a significant difference</p>
<p><span class="math inline">\(H_0:\)</span> For participants in the Living Well Multicultural – Lifestyle Modification Program, the mean BMI after the program is not significantly different than the mean BMI before the program.</p>
<p><span class="math inline">\(H_A:\)</span> For participants in the Living Well Multicultural – Lifestyle Modification Program, the mean BMI after the program is significantly lower than the mean BMI before the program.</p>
<p>We can express this in mathematical notation:</p>
<p><span class="math inline">\(H_0:\)</span> <span class="math inline">\(\mu_{diff}=0\)</span></p>
<p><span class="math inline">\(H_A:\)</span> <span class="math inline">\(\mu_{diff} &gt; 0\)</span></p>
<p>where <span class="math inline">\(diff = BMI_{Baseline} - BMI_{Post Week 8}\)</span>. Now we need to calculate the difference between the baseline BMI and Post Week 8 BMI . We can do that with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>living_well_wide<span class="sc">$</span>diff <span class="ot">&lt;-</span> (living_well_wide<span class="sc">$</span>Baseline <span class="sc">-</span> living_well_wide<span class="sc">$</span>Post_week8)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>living_well_wide<span class="sc">$</span>diff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  0.20  0.20  0.90  1.20  0.10  0.20  0.80  0.50  0.10  0.10  0.00  0.40
 [13]  1.50  0.30  0.30 -0.10  0.10  0.80  1.10  1.20  0.80  0.30 -0.06  0.26
 [25]  0.45  0.53  0.32  0.42 -0.01 -0.03  0.31  0.60  0.50  0.70  0.40  0.40
 [37]  1.50  0.40  0.40  0.30  0.40  0.40  0.30  0.70  0.00  1.60  1.00 -0.20
 [49] -0.60  0.40  0.20  0.10  0.40  1.00  0.50  1.20  0.50  0.30  0.00 -0.10
 [61]  0.70 -1.70 -4.90  0.40  0.10  0.20  0.30  0.00  0.70  0.90  0.10  0.90
 [73]  0.60  0.10  1.70  0.40  0.10  0.30  1.10  0.20  0.10  0.20  0.00  0.40
 [85]  0.10 -0.40  0.00  0.40  0.20  0.00  0.30 -0.10  0.00  0.80  1.00  0.80
 [97]  0.40 -0.20  1.50  0.30  0.30 -0.20  0.70  0.40 -0.30  1.40  0.70  0.60
[109]  0.50  0.30  0.30  1.80 -0.10  1.00  0.50  0.40 -0.20  0.90  0.50  0.50
[121]  1.00  0.50  0.80  0.30  1.30  0.60  1.10  0.70  0.70  0.60  0.90  0.80
[133]  0.80 -0.80  0.30  0.20  1.40  2.30 -0.70  0.70  1.10  0.40 -0.90  1.20
[145] -1.70  2.00  0.00  1.40  1.40  3.60  0.80  0.40  0.80  1.00  0.40  0.50
[157] -0.80  0.80  0.70  1.40  1.30  1.00  0.70 -0.20  0.70 -1.50 -2.10  2.00
[169] -1.10 -0.60  0.80  1.00  0.10 -0.40  2.10 -0.30  0.90 -0.30  0.70 -0.30
[181] -2.90 -0.50 -0.80  1.60  0.50  1.30  0.60  0.30  0.00  0.00  0.50  0.10
[193]  0.60  0.00  0.90  0.30  0.90  0.00  0.00 -0.40 -0.40 -1.40  0.30  0.10
[205] -1.60  0.00  0.20  0.50  0.20  0.20  0.00  0.00  0.50  0.00  0.20  0.40
[217] -0.30  0.30  0.00  0.10  0.40 -0.50  0.30  0.40 -0.90  0.00 -0.20 -0.50
[229]  0.80  0.30  0.60  0.10  0.10 -0.40  0.20  0.20  0.10  0.30  0.10  0.20
[241]  0.20  0.00  0.10  0.40  0.40  0.00  0.00  0.10  0.00  0.20  0.90  0.90
[253]  0.30  0.70  0.40  0.70  0.70  0.00  0.40  1.00  0.90  0.30  0.00  1.20
[265] -0.40  0.30  1.40  0.50 -0.30 -0.40 -0.10 -0.30  0.30 -0.40 -0.20  0.70
[277]  0.40  0.10  1.30  0.00  0.80 -0.70  0.40  0.30  0.00  0.40  0.50  0.00
[289] -2.00  0.40  0.40  0.40  0.60  0.60 -0.10  0.30  0.50  0.60 -0.30  0.30
[301] -0.30 -0.30  0.20  1.00  0.30  1.00  0.80 -0.20 -0.80  0.00 -1.00 -0.40
[313]  0.00  0.90 -0.50  0.20 -0.90 -0.30  0.60  0.10  0.40  0.10  0.30  0.50
[325]  1.20 -0.10  0.20  0.10  0.70  0.20  0.00  0.80  0.90 -0.90  0.50  0.20
[337]  0.30  0.50  0.80  1.40  0.60 -0.40  0.30  0.80  0.80 -0.20  0.10  0.20
[349] -0.10  0.80  0.50 -0.10  1.00  0.10  0.20  0.60  0.10 -0.80  0.30  0.20
[361]  0.60  0.70  0.80  0.70  0.20  0.90  0.60  0.60  0.40  1.10  1.60 -0.20
[373] -0.30  0.70  0.10 -0.60  0.30  0.30  0.30  0.30 -0.10  0.50  0.80 -0.30
[385]  0.70 -0.30  0.90 -0.90  0.10  1.50  1.60  0.90 -0.20 -0.30  0.70  1.20
[397]  1.90  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00 -0.10 -0.70  0.00
[409]  0.00  0.00 -0.10  0.70 -0.50  0.80  0.20  0.30  0.20  0.20  0.60  0.00
[421]  0.40  0.60  0.20  0.00  0.40  0.40  0.40 -0.50 -0.60 -0.50  1.10 -1.00
[433]  0.10  0.20  0.70  0.30 -1.10  0.60 -0.30 -0.80 -0.10  0.00 -0.30  0.30
[445]  0.70  0.10  0.20 -1.30 -0.30 -0.30 -0.10  1.20  0.60  0.30 -0.30  1.60
[457]  1.20  0.20  0.00  0.70  0.20  0.00  0.00  0.20 -0.10  0.40  0.30  0.60
[469]  0.30  1.20  1.40  0.70  0.20  0.10  0.00  0.20 -0.20 -0.50 -0.10  0.20
[481] -0.30 -0.30 -2.10  0.70 -0.90 -1.30  1.00  0.30  0.00  0.00 -0.70  0.90
[493] -0.90  0.20 -0.20 -0.40  0.40 -0.20 -0.40 -0.70  0.80  1.10 -0.40  1.80
[505]  0.30 -0.30  0.70  0.40  2.20  0.20  0.60  0.10  3.70  1.10  0.00  1.30
[517]  0.80  0.50  0.40  0.80  0.10  0.40 -0.10  0.10  0.70 -1.20  0.40  0.50
[529]  0.10  0.20  0.10  0.20  0.00  0.00  0.00  0.50  0.30  0.00  0.80 -0.20
[541]  0.00  0.80 -0.10  0.40  0.10 -3.80  0.90  0.20  0.00</code></pre>
</div>
</div>
<p>We can attach the data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(living_well_wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can check for skewness and normality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>living_well_wide, <span class="fu">aes</span>(<span class="at">y=</span>diff, <span class="at">x=</span><span class="st">""</span>))<span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"mistyrose"</span>, <span class="at">col=</span><span class="st">"pink4"</span>)<span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>living_well_wide, <span class="fu">aes</span>(<span class="at">sample=</span>diff))<span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>(<span class="at">col=</span><span class="st">"navyblue"</span>)<span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>(<span class="at">col=</span><span class="st">"steelblue"</span>)<span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Theoretical quantiles"</span>, <span class="at">y=</span><span class="st">"Sample quantiles"</span>)<span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can now run our t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Baseline, Post_week8, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Baseline and Post_week8
t = 9.0896, df = 548, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is greater than 0
95 percent confidence interval:
 0.2275603       Inf
sample estimates:
mean difference 
      0.2779417 </code></pre>
</div>
</div>
<p>The p-value (<span class="math inline">\(t_{548}=9.09, p=2.2*10^{-16}\)</span>) is much less than the 5% significance level (p&lt;0.05). We used <code>greater</code> because our hypothesis was that BMI would go down after the program. The t test calculates the difference as baseline minus post week 8, so if BMI really decreased, that difference would be positive. Using greater than tells R to test whether the average of those differences is greater than zero, meaning baseline values were higher than post week 8 values.</p>
<p>Therefore, the mean BMI after the program is significantly lower than the mean BMI before the program.</p>
<p>Let’s generate a two-sided paired t-test to get the confidence interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Baseline, Post_week8, <span class="at">paired =</span> <span class="cn">TRUE</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Baseline and Post_week8
t = 9.0896, df = 548, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.2178774 0.3380060
sample estimates:
mean difference 
      0.2779417 </code></pre>
</div>
</div>
<p>With 95% confidence, there ia mean BMI difference of 0.22 and 0.34 BMI Because this interval includes zero, the data supports a real difference before and after the program. <strong>Note that if 0 was <u>IN</u> in the confidence interval, this would suggest there is <u>not</u> a significant difference</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(living_well_wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="anova" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> ANOVA</h1>
<p>For the second part of this lesson, we are going to explore ANOVA.</p>
<p>We want to do ANOVA when we are comparing three or more groups (or categories) against a continuous response variable.</p>
<p>We can continue on with our <code>living_well</code> dataset, but instead refocus our research question and restructure the dataset accordingly.</p>
<p>An example of a research question we might ask with ANOVA is whether education level impacts post program BMI.</p>
<p>Let’s rewrite our hypotheses.</p>
<p><span class="math inline">\(H_0:\)</span> There is no difference in mean BMI at post week 8 between education groups in the Living Well Multicultural – Lifestyle Modification Program.</p>
<p><span class="math inline">\(H_A:\)</span> At least one education group has a different mean BMI at post week 8.</p>
<p>We can express this in mathematical notation:</p>
<p><span class="math inline">\(H_0:\)</span> <span class="math inline">\(\mu_1=\mu_2=\mu_3=...=\mu_7\)</span></p>
<p><span class="math inline">\(H_A:\)</span> At least one <span class="math inline">\(\mu_i\)</span> is different.</p>
<p>Let’s tidy up the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>living_well_aov <span class="ot">&lt;-</span> living_well_clean <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> <span class="fu">c</span>(ID, Education),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> Time,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> BMI,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_glue =</span> <span class="st">"{str_replace_all(Time, ' ', '_')}"</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s be sure to remove any <code>999</code> values. How can we do this?</p>
<div class="webex-solution">
<button>
I need a hint
</button>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>living_well_aov <span class="ot">&lt;-</span> living_well_aov <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Education =</span> <span class="fu">factor</span>(<span class="fu">replace</span>(Education, Education <span class="sc">==</span> <span class="st">"999"</span>, <span class="cn">NA</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Baseline =</span> <span class="fu">na_if</span>(Baseline, <span class="dv">999</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Post_week8 =</span> <span class="fu">na_if</span>(Post_week8, <span class="dv">999</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(Baseline, Post_week8, Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Remember, because <code>Education</code> is a categorical variable, <code>999</code> will be stored as a string rather than a numerical variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(living_well_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [521 × 4] (S3: tbl_df/tbl/data.frame)
 $ ID        : Factor w/ 554 levels "ABA200879","ABD 010160",..: 295 294 38 296 191 192 297 10 453 452 ...
 $ Education : Factor w/ 7 levels "Bachelor degree",..: 5 5 3 5 4 4 1 3 1 1 ...
 $ Baseline  : num [1:521] 19.9 18.8 34.6 20.8 30.3 24.5 21.5 26.2 19.6 19.9 ...
 $ Post_week8: num [1:521] 19.7 18.6 33.7 19.6 30.2 24.3 20.7 25.7 19.5 19.8 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(living_well_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<p>For a one-way ANOVA we need to check</p>
<ul>
<li><p>Independence</p></li>
<li><p>Normality of the response variable for each population.</p></li>
<li><p>All populations have the same standard deviation.</p></li>
</ul>
<p>To determine these:</p>
<ul>
<li><p>We typically assume independence, as long as e.g., a random sample has been collected and each observation is a unique case/subject/participant.</p></li>
<li><p>We can determine normality by considering side-by-side boxplots, or a quantile-quantile plot.</p></li>
<li><p>We can compute the standard deviation for each group using <code>aggregate()</code> like we tried last week. A rule of thumb is that we are likely safe if the largest standard deviation is less than double the smallest standard deviation.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(living_well_aov, <span class="fu">aes</span>(<span class="at">x=</span>Education, <span class="at">y=</span>Post_week8))<span class="sc">+</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"cadetblue1"</span>,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"aquamarine2"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"steelblue1"</span>,</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"cyan2"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"dodgerblue1"</span>,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"deepskyblue1"</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"slateblue1"</span>))<span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span>   </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>living_well_aov, <span class="fu">aes</span>(<span class="at">sample=</span>Post_week8))<span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>()<span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()<span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Post_week8<span class="sc">~</span>Education, <span class="at">FUN=</span>sd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Education Post_week8
1                 Bachelor degree   6.393231
2 Certificate (trade or business)   8.088750
3     Diploma or Associate degree   6.313799
4     High school (up to 4 years)   8.743657
5     High school (up to 6 years)   6.760607
6              Posgraduate degree   4.549479
7                  Primary school   7.602748</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Post_week8<span class="sc">~</span>Education, <span class="at">FUN=</span>length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Education Post_week8
1                 Bachelor degree         93
2 Certificate (trade or business)         54
3     Diploma or Associate degree         60
4     High school (up to 4 years)         69
5     High school (up to 6 years)         95
6              Posgraduate degree         48
7                  Primary school        102</code></pre>
</div>
</div>
<p>Based on these outputs, do you think the necessary conditions for our one-way ANOVA are met?</p>
<div class="webex-solution">
<button>
I need a hint
</button>
<p>Each individual is unique and only sampled randomly once, so independence is met.</p>
<p>The scatter in the q-q plot is reasonably straight and the boxplots are reasonably symmetrical about the median, so a normal distribution is met.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fl">4.55</span><span class="sc">/</span><span class="fl">8.74</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.520595</code></pre>
</div>
</div>
<p><span class="math inline">\(4.55/8.74 = 0.52 &lt; 2\)</span></p>
<p>The largest standard deviation is less than twice that of the smallest, so constant variance is met.</p>
</div>
<p>We can now run an ANOVA on the data. Note these are two lines of code and thus need to be run one after the other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>mod.aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(Post_week8<span class="sc">~</span>Education, <span class="at">data =</span> living_well_aov)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mod.aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Post_week8
           Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
Education   6   771.1 128.516  2.5519 0.01915 *
Residuals 514 25885.8  50.362                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The key values we can see are the F statistic, and the p-value that is associated with that. Given that our p-value is less than 0.05, we have evidence to reject the null hypothesis.</p>
<p>In regards to our research question we can say that:</p>
<p><strong>There is a significant difference in mean BMI for at least some education levels.</strong></p>
<p>We need to carefully check for differences between each group (correcting for multiple comparisons) to determine what is happening. To do this we can use a pairwise t-test with a Bonferroni correction. We use the Bonferroni adjustment because multiple pairwise comparisons increase the chance of finding a significant result just by chance. The adjustment makes the significance threshold more conservative, helping to control the overall Type I error rate (i.e.&nbsp;false positives) so that any detected differences are more likely to be real.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(Post_week8,Education,<span class="at">p.adj=</span><span class="st">'bonf'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  Post_week8 and Education 

                                Bachelor degree Certificate (trade or business)
Certificate (trade or business) 0.254           -                              
Diploma or Associate degree     1.000           1.000                          
High school (up to 4 years)     0.581           1.000                          
High school (up to 6 years)     1.000           0.449                          
Posgraduate degree              1.000           0.066                          
Primary school                  1.000           1.000                          
                                Diploma or Associate degree
Certificate (trade or business) -                          
Diploma or Associate degree     -                          
High school (up to 4 years)     1.000                      
High school (up to 6 years)     1.000                      
Posgraduate degree              0.922                      
Primary school                  1.000                      
                                High school (up to 4 years)
Certificate (trade or business) -                          
Diploma or Associate degree     -                          
High school (up to 4 years)     -                          
High school (up to 6 years)     1.000                      
Posgraduate degree              0.147                      
Primary school                  1.000                      
                                High school (up to 6 years) Posgraduate degree
Certificate (trade or business) -                           -                 
Diploma or Associate degree     -                           -                 
High school (up to 4 years)     -                           -                 
High school (up to 6 years)     -                           -                 
Posgraduate degree              1.000                       -                 
Primary school                  1.000                       1.000             

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>Since there are seven education groups, the pairwise t-tests compare the mean post-week-8 BMI between each pair of education levels. This means we can look at differences such as Bachelor degree vs Certificate (trade or business), Bachelor degree vs Diploma or Associate degree, or High school (up to 4 years) vs Postgraduate degree, and so on. The table shows the p-values for each of these comparisons, adjusted using the Bonferroni method.</p>
<p>The ANOVA showed a significant overall difference in post week 8 BMI between education groups (p = 0.019), meaning that at least one group had a different mean BMI compared to the others. However, when pairwise t tests were run with a Bonferroni adjustment, none of the individual group comparisons were statistically significant. This suggests that while there may be small differences in BMI across education levels overall, these differences are not strong enough between specific groups to remain significant once the stricter adjustment for multiple comparisons is applied.</p>
<p>Finally, lets calculate some confidence intervals for each group. If two groups have confidence intervals that do not overlap, it suggests their mean BMI values are likely different. If the intervals overlap, we can’t say there is a clear difference between those groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate CIs for each group</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>mod.aov.ci <span class="ot">&lt;-</span> <span class="fu">lm</span>(Post_week8<span class="sc">~</span>Education<span class="dv">-1</span>, <span class="at">data =</span> living_well_aov)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>ci<span class="ot">&lt;-</span><span class="fu">confint</span>(mod.aov.ci)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                            2.5 %   97.5 %
EducationBachelor degree                 26.50376 29.39517
EducationCertificate (trade or business) 29.11016 32.90466
EducationDiploma or Associate degree     27.80344 31.40322
EducationHigh school (up to 4 years)     28.76072 32.11754
EducationHigh school (up to 6 years)     26.78538 29.64620
EducationPosgraduate degree              24.81475 28.83942
EducationPrimary school                  27.75092 30.51182</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate means for each group</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>mean_lw<span class="ot">&lt;-</span><span class="fu">aggregate</span>(Post_week8 <span class="sc">~</span> Education, <span class="at">data =</span> living_well_aov, <span class="at">FUN =</span> mean)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Add the means and CIs together in a dataframe to plot</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>values<span class="ot">&lt;-</span><span class="fu">cbind</span>(mean_lw,ci)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Rename the column headings and row headings</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(values)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"group"</span>,<span class="st">"mean"</span>, <span class="st">"lower"</span>,<span class="st">"upper"</span>)</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(values)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>)</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            group     mean    lower    upper
1                 Bachelor degree 27.94946 26.50376 29.39517
2 Certificate (trade or business) 31.00741 29.11016 32.90466
3     Diploma or Associate degree 29.60333 27.80344 31.40322
4     High school (up to 4 years) 30.43913 28.76072 32.11754
5     High school (up to 6 years) 28.21579 26.78538 29.64620
6              Posgraduate degree 26.82708 24.81475 28.83942
7                  Primary school 29.13137 27.75092 30.51182</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create errorbar plot</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>values, <span class="fu">aes</span>(<span class="at">x=</span>group, <span class="at">y=</span>mean))<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>lower, <span class="at">ymax=</span>upper), <span class="at">linewidth=</span><span class="fl">1.5</span>, <span class="at">col=</span><span class="st">"green3"</span>)<span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"darkgreen"</span>)<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">"BMI (mean+CIs)"</span>) <span class="sc">+</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="chapter5_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Because these intervals overlap, it suggests that the mean post-week-8 BMI values are quite similar across education groups. There isn’t clear separation between any of the groups, which means we can’t say any one education group’s mean BMI is significantly different from the others based on these confidence intervals.</p>
<p>Therefore, the ANOVA indicated a significant overall difference in post week 8 BMI across education levels (p = 0.019), so the null hypothesis of equal means was rejected. However, post hoc tests and confidence intervals showed that no specific group comparisons were significant, suggesting that while some variation exists across education levels, the differences are small.</p>


</section>

</main> <!-- /main -->
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  var t = document.getElementsByClassName("webex-total_correct");
  for (var i = 0; i < t.length; i++) {
    p = t[i].parentElement;
    var correct = p.getElementsByClassName("webex-correct").length;
    var solvemes = p.getElementsByClassName("webex-solveme").length;
    var radiogroups = p.getElementsByClassName("webex-radiogroup").length;
    var selects = p.getElementsByClassName("webex-select").length;

    t[i].innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");

  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* check answers */
check_func = function() {
  console.log("webex: check answers");

  var cl = this.parentElement.classList;
  if (cl.contains('unchecked')) {
    cl.remove("unchecked");
    this.innerHTML = "Hide Answers";
  } else {
    cl.add("unchecked");
    this.innerHTML = "Show Answers";
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");

  var cl = this.classList

  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;

  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }

  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }

  update_total_correct();
}

window.onload = function() {
  console.log("webex onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  var check_sections = document.getElementsByClassName("webex-check");
  console.log("check:", check_sections.length);
  for (var i = 0; i < check_sections.length; i++) {
    check_sections[i].classList.add("unchecked");

    let btn = document.createElement("button");
    btn.innerHTML = "Show Answers";
    btn.classList.add("webex-check-button");
    btn.onclick = check_func;
    check_sections[i].appendChild(btn);

    let spn = document.createElement("span");
    spn.classList.add("webex-total_correct");
    check_sections[i].appendChild(spn);
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;

    solveme[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }

  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
    selects[i].insertAdjacentHTML("afterend", " <span class='webex-icon'></span>")
  }

  update_total_correct();
}

</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter4.html" class="pagination-link" aria-label="t-tests: one sample and two sample">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests: one sample and two sample</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>